apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authorization-server-monitor
  namespace: demo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authorization-server
  endpoints:
  - interval: 5s
    port: service
    path: /actuator/prometheus
  namespaceSelector:
    any: true