apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.1.9
    helm.sh/chart: fluent-bit-0.38.0
data:
  custom_parsers.conf: |
    [PARSER]
        Name        spring_pattern
        Format      regex
        Regex       ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}:\d{3}) \[(?<loglevel>\w+)\] \[(?<user>.+?)\] \[(?<thread>.+?)\] \[(?<traceId>.+?)\] \[(?<spanId>.+?)\] \[(?<trace_flags>.+?)\] (?<class>\w+).(?<method>\w+):(?<line>\d+): (?<message>.+)$
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S:%L
  fluent-bit.conf: |
    [SERVICE]
       Daemon Off
       Flush 1
       Log_Level info
       Parsers_File custom_parsers.conf
       HTTP_Server On
       HTTP_Listen 0.0.0.0
       HTTP_Port 2020
       Health_Check On
    [INPUT]
       Name tail
       Path  /var/log/pods/*/*/*.log
       multiline.parser docker, cri
       Tag var.*
       Mem_Buf_Limit 5MB
       Skip_Long_Lines On
    [FILTER]
       Name kubernetes
       Match kube.*
       Merge_Log On
       Keep_Log Off
       K8S-Logging.Parser    On
       K8S-Logging.Exclude On
    [FILTER]
       Name nest
       Match kube.*
       Operation lift
       Nested_under kubernetes
       Add_prefix   kubernetes_
    [FILTER]
       Name grep
       Match kube.*
       Exclude kubernetes_container_name fluent-bit
    [FILTER]
       Name     throttle
       Match    *
       Rate     800
       Window   3
       Print_Status  true
       Interval 30s
    [OUTPUT]
       name loki
       match *
       host loki.tracing.svc
       port 3100
       labels job=fluentbit
       label_keys $trace_id
       auto_kubernetes_labels on
    [OUTPUT]
       Name stdout
       Match *